//! Clarification types for intent analysis and question flow.

use serde::{Deserialize, Serialize};

/// How a question should be presented.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum QuestionType {
    /// Pick exactly one option.
    SingleSelect,
    /// Pick one or more options.
    MultiSelect,
}

/// A clarification question generated by the LLM.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Question {
    /// Unique question ID (e.g. "q1").
    pub id: String,
    /// How to present the question.
    pub question_type: QuestionType,
    /// The question text.
    pub question: String,
    /// Available options (always includes custom answer option).
    pub options: Vec<String>,
    /// Why this question matters.
    pub reason: String,
}

/// Result of the clarification question generation.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ClarificationResult {
    /// Questions to ask the user.
    pub questions: Vec<Question>,
    /// AI-inferred assumptions.
    pub assumptions: Vec<String>,
    /// Confidence score (0.0 - 1.0).
    pub confidence: f32,
    /// Whether current info is sufficient to proceed without questions.
    #[serde(default)]
    pub sufficient_for_planning: bool,
}

/// Collected context for planning.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct PlanningContext {
    /// Original user prompt.
    pub intent: String,
    /// Whether this is a new project or existing code.
    pub mode: String,
    /// User's answers to clarification questions.
    pub answers: Vec<(String, String)>,
    /// AI-inferred assumptions.
    pub assumptions: Vec<String>,
    /// Confidence score.
    pub confidence: f32,
}

impl PlanningContext {
    /// Build an enriched prompt that includes answers and assumptions.
    pub fn to_enriched_prompt(&self) -> String {
        let mut parts = vec![self.intent.clone()];

        if !self.answers.is_empty() {
            parts.push("\nUser requirements:".into());
            for (question, answer) in &self.answers {
                parts.push(format!("- {question}: {answer}"));
            }
        }

        if !self.assumptions.is_empty() {
            parts.push("\nAssumptions:".into());
            for a in &self.assumptions {
                parts.push(format!("- {a}"));
            }
        }

        parts.join("\n")
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn planning_context_enriched_prompt() {
        let ctx = PlanningContext {
            intent: "create a todo app".into(),
            mode: "greenfield".into(),
            answers: vec![
                ("Framework".into(), "React + Vite".into()),
                ("Styling".into(), "Tailwind CSS".into()),
            ],
            assumptions: vec!["TypeScript".into()],
            confidence: 0.85,
        };
        let prompt = ctx.to_enriched_prompt();
        assert!(prompt.contains("create a todo app"));
        assert!(prompt.contains("React + Vite"));
        assert!(prompt.contains("Tailwind CSS"));
        assert!(prompt.contains("TypeScript"));
    }

    #[test]
    fn planning_context_no_extras() {
        let ctx = PlanningContext {
            intent: "fix the bug".into(),
            mode: "brownfield".into(),
            answers: vec![],
            assumptions: vec![],
            confidence: 0.9,
        };
        assert_eq!(ctx.to_enriched_prompt(), "fix the bug");
    }

    #[test]
    fn question_serde() {
        let q = Question {
            id: "q1".into(),
            question_type: QuestionType::SingleSelect,
            question: "Which framework?".into(),
            options: vec!["React".into(), "Vue".into(), "Other".into()],
            reason: "determines setup".into(),
        };
        let json = serde_json::to_string(&q).unwrap();
        let parsed: Question = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed.id, "q1");
        assert_eq!(parsed.options.len(), 3);
    }
}
