//! Structure check — run commands from the plan to verify scaffold compiles.

use std::path::Path;
use std::process::Command;

/// Result of a structure check.
#[derive(Debug)]
pub struct CheckResult {
    /// Whether all commands passed.
    pub passed: bool,
    /// Combined output from failed commands.
    pub errors: String,
}

/// Run structure check commands from the plan.
///
/// These commands are generated by the planner (language-agnostic).
pub fn run_check(commands: &[String], project_root: &Path) -> CheckResult {
    if commands.is_empty() {
        return CheckResult { passed: true, errors: String::new() };
    }

    let mut all_passed = true;
    let mut errors = Vec::new();

    for cmd in commands {
        let output = Command::new("sh")
            .arg("-c")
            .arg(cmd)
            .current_dir(project_root)
            .env("CI", "true")
            .output();

        match output {
            Ok(o) if o.status.success() => {}
            Ok(o) => {
                all_passed = false;
                let stderr = String::from_utf8_lossy(&o.stderr);
                let stdout = String::from_utf8_lossy(&o.stdout);
                errors.push(format!("$ {cmd}\n{}\n{}", stdout.trim(), stderr.trim()));
            }
            Err(e) => {
                all_passed = false;
                errors.push(format!("$ {cmd}\nfailed to execute: {e}"));
            }
        }
    }

    CheckResult {
        passed: all_passed,
        errors: errors.join("\n\n"),
    }
}

/// Run an install command from the plan.
pub fn run_install(command: &str, project_root: &Path) -> bool {
    let output = Command::new("sh")
        .arg("-c")
        .arg(command)
        .current_dir(project_root)
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::piped())
        .output();

    matches!(output, Ok(o) if o.status.success())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn check_empty_commands_passes() {
        let dir = tempfile::tempdir().unwrap();
        let result = run_check(&[], dir.path());
        assert!(result.passed);
    }

    #[test]
    fn check_true_passes() {
        let dir = tempfile::tempdir().unwrap();
        let result = run_check(&["true".into()], dir.path());
        assert!(result.passed);
    }

    #[test]
    fn check_false_fails() {
        let dir = tempfile::tempdir().unwrap();
        let result = run_check(&["false".into()], dir.path());
        assert!(!result.passed);
    }

    #[test]
    fn install_true_succeeds() {
        let dir = tempfile::tempdir().unwrap();
        assert!(run_install("true", dir.path()));
    }
}
